### ISSUE TITLE
Cannot read properties of undefined (reading 'pageTitle')

### ISSUE THREAD

**Issue by beyondlex** [PacoVK/antora-confluence#35]
When I execute the antora command, i get the following error:

```
info:     Publishing Dash to Confluence
info:     Initializing state
info:     Decoding Confluence state
info:     Removing untracked pages
info:     Publishing pages
info:     Processing worktree.html
[17:30:07.783] FATAL (antora): Cannot read properties of undefined (reading 'pageTitle')
```

Here is my configuration:

```yaml
output:
  destinations:
    - provider: fs
    - provider: antora-confluence
      confluence-api: http://.../rest/api
      confluence-space: 'myspace'
      ancestor-id: 1016484
      filter:
        - path: tool/git
```

Is there something wrong with my configuration? Thank you for your help!

**Comment by beyondlex** [comment]
I forked the code and debugged it. I found that the issue lies with the filter. The filter restricts the pages involved in the current generation, but the pages reference other pages that are not included in this generation, causing the error.

**Comment by beyondlex** [comment]
Yes, I completely agree with your point of view. Some people prefer to ignore non-existent references to prioritize passing the compilation, while others prefer the compilation to fail to highlight which reference files were missed. Providing an option is the right approach.

**Comment by PacoVK** [comment]
just checking to avoid duplicate efforts, @beyondlex are you working on this and come up with a PR at some point? (no time pressure) :)

**Comment by slonopotamus** [comment]
I am observing the same error without using any filters.

```yaml
output:
  destinations:
    - provider: fs
    - provider: antora-confluence
      confluence-api: <bla>
      confluence-space: <bla>
      show-banner: true
      ancestor-id: <bla>
```

I am observing the same error without using any filters.

```yaml
output:
  destinations:
    - provider: fs
    - provider: antora-confluence
      confluence-api: <bla>
      confluence-space: <bla>
      show-banner: true
      ancestor-id: <bla>
```

```
info:     Processing <bla>\index.html
[12:16:12.127] FATAL (antora): Cannot read properties of undefined (reading 'pageTitle')
    Cause: TypeError
        at C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\lib\transformer\LinkTransformer.js:101:140
        at Array.forEach (<anonymous>)
        at rewriteInternalLinks (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\lib\transformer\LinkTransformer.js:80:41)
        at convertHtmlToConfluence (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\lib\service\HtmlToConfluenceConverter.js:22:69)
        at processPage (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\lib\service\PageService.js:288:94)
        at publish (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\lib\service\PageService.js:178:40)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async publishToConfluence (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\antora-confluence\dist\index.js:49:9)
        at async Promise.all (index 1)
        at async generateSite (C:\Users\marat\OneDrive\Documents\<bla>\docs\node_modules\@antora\site-generator\lib\generate-site.js:53:12)
```

If I read the stacktrace properly, antora-confluence sees a link to `index.adoc` in module root somewhere. Though I believe the only place where it is linked is in `nav.adoc`.
