### ISSUE TITLE
Mapping structure not working

### ISSUE THREAD

**Issue by Blackstonecoden** [PacoVK/antora-confluence#56]
## Issue Overview

I am attempting to use the `mapper` (or the default mapper) to generate the page structure for my Antora documentation. To set up a testing environment, I used the example project from Antora. However, I noticed that the expected page structure isn't appearing in the Confluence page.

### Expected Result:
![Expected Result](https://github.com/user-attachments/assets/41a93e34-00bd-4dd0-8417-a5ee80c36c26)

### The Result I Am Getting:
![Actual Result](https://github.com/user-attachments/assets/cfc51cb9-9150-48d2-a5b7-1aa1cfda88bd)

### `antora-playbook.yml`

```yaml
site:
  title: Antora Docs
  start_page: component-b::index.adoc
  url: https://docs.domain.tld
content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  destinations:
    - provider: fs
    - provider: antora-confluence
      confluence-api: https://<hidden>.atlassian.net
      confluence-space: <hidden>
      show-banner: true
      ancestor-id: <hidden>
```

### `package.json` version
```
{
  "devDependencies": {
    "antora": "3.1.9",
    "antora-confluence": "^0.4.0",
    "http-server": "^14.1.1"
  }
}
```
