### ISSUE TITLE
When using @antora/lunr-extension the search-index.js is not there

### ISSUE THREAD

**Issue by bladnor** [PacoVK/antora-confluence#58]
When using @antora/lunr-extension the search-index.js is either not generated or overwritten when the provider antora-confluence is configured.
Snippet from antora-playbook.yml:
```
...
antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
output:
  clean: true
  dir: ./antora-build
  destinations:
    - provider: antora-confluence
...
```

Is there a workaround for this?
